apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: c-template
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: c-template 
  name: c-template
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: c-template 
